### ISSUE TITLE
URGENT

### ISSUE THREAD

**Issue by jerry-appliedAIstudio** [dxc-technology/AI-Remote-Worker-Assistant#22]
im not able to interact with the chat unless the calculator is showing

**Comment by hemanth-arikatla** [comment]
It's because the calculator is hiding and overlapping with the division of the chat. Once the calculator pops up, overlapping goes away and chat works properly. I am trying to move the chatbox to the top, to remove this overlapping all the time.

**Comment by hemanth-arikatla** [comment]
I made it functional by adjusting it's height so that it won't overlap with the navigation bar. But still, the layout is not similar to the proposed design. If I try to move the navigation bar away so that it won't overlap with the chatbot, navbar is totally invisible. we might have to discuss this with Angeli to see if we could move it away properly. I tried to do it, but failed.

**Comment by hemanth-arikatla** [comment]
fixed it.
